#!/usr/bin/env ruby
# A very simple, very naive parser

raise "No file provided on command line." if ARGV.empty?

require './naive_parser'


filename  = ARGV.first
plaintext = File.read(file_to_parse)

NaiveParser.new(plaintext)
