#!/usr/bin/env ruby
# A very simple, very naive parser

raise "No file provided on command line." if ARGV.empty?

require './lib/naive_parser'


filename  = ARGV.first
plaintext = File.open(filename, File::RDONLY).read

NaiveParser.new(plaintext)
